import scrollPage from "./components/scrollPage.js";
import paddingTopHeader from "./components/paddingTopHeader.js";
import bgChangeHover from "./components/bgChangeHover.js";
import accordions from "./components/accordions.js";
import newsFilterSlider from "./components/newsFilterSlider.js";
import openSearchForm from "./components/openSearchForm.js";
import modals from './components/modals.js';
import phoneMask from "./components/phoneMask.js";
import createSlider from "./components/slider.js";
import searchOddAndEvenItems from "./components/searchOddAndEvenItems.js";
import copyLink from "./components/copyLink.js";

scrollPage();
paddingTopHeader();
bgChangeHover();
accordions();
newsFilterSlider();
openSearchForm();
modals();
phoneMask();
createSlider();
searchOddAndEvenItems();
copyLink();